Worktastic/Models/JobPosting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Worktastic.Models
{
    public class JobPosting
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public string JobLocation { get; set; }
        public string Description { get; set; }
        public int Salary { get; set; }
        public DateTime StartDate { get; set; }
        public string CompanyName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactMail { get; set; }
        public string ContactWebsite { get; set; }
        public byte[] CompanyImage { get; set; }
        // Definiere eine Variable, die es erlaubt nach diesem aus der DB zu suschen:
        public string OwnerUsername { get; set; }
    }
}

Worktastic/Controllers/JobPostingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Worktastic.Data;
using Worktastic.Models;

namespace Worktastic.Controllers
{
    [Authorize]
    public class JobPostingController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JobPostingController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                var allPostings = _context.JobPostings.ToList();
                return View(allPostings);
            }

            var jobPostingsFromDb = _context.JobPostings.Where(x => x.OwnerUsername == User.Identity.Name).ToList();

            return View(jobPostingsFromDb);
        }

        public IActionResult CreateEditJobPosting(int id)
        {
            if (id != 0)
            {
                var jobPostingFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == id);

                if ((jobPostingFromDb.OwnerUsername != User.Identity.Name) && !User.IsInRole("Admin"))
                {
                    return Unauthorized();
                }

                if (jobPostingFromDb != null)
                {
                    return View(jobPostingFromDb);
                }
                else
                {
                    return NotFound();
                }
            }

            return View();
        }

        public IActionResult CreateEditJob(JobPosting jobPosting, IFormFile file)
        {
            jobPosting.OwnerUsername = User.Identity.Name;
            if (file != null)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    var bytes = ms.ToArray();
                    jobPosting.CompanyImage = bytes;
                }
            }

            if (jobPosting.Id == 0)
            {
                _context.JobPostings.Add(jobPosting);
            }
            else
            {
                // Entity Framework query, whereby search and give us that element which we had
                // given above (jobPosting.Id):
                var jobFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == jobPosting.Id);
                if (jobFromDb == null)
                {
                    // Im Falle eines schweren Pogrammierfehlers gib eine 404-Seite aus:
                    return NotFound();
                }

                jobFromDb.CompanyImage = jobPosting.CompanyImage;
                jobFromDb.CompanyName = jobPosting.CompanyName;
                jobFromDb.ContactMail = jobPosting.ContactMail;
                jobFromDb.ContactPhone = jobPosting.ContactPhone;
                jobFromDb.ContactWebsite = jobPosting.ContactWebsite;
                jobFromDb.Description = jobPosting.Description;
                jobFromDb.JobLocation = jobPosting.JobLocation;
                jobFromDb.JobTitle = jobPosting.JobTitle;
                jobFromDb.Salary = jobPosting.Salary;
                jobFromDb.StartDate = jobPosting.StartDate;
                // jobFromDb.OwnerUsername = jobPosting.OwnerUsername;
            }
            // Add new job if not editing:
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteJobPostingById(int id)
        {
            if (id == 0)
                return BadRequest();

            var jobPostingsFromDb = _context.JobPostings.SingleOrDefault(x => x.Id == id);

            if (jobPostingsFromDb == null)
            {
                return NotFound();
            }
            _context.JobPostings.Remove(jobPostingsFromDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Worktastic/Views/JobPosting/CreateEditJobPosting.cshtml
@model Worktastic.Models.JobPosting
@{
    ViewData["Title"] = "Erstellen oder bearbeiten";

}

<form asp-controller="JobPosting" asp-action="CreateEditJob" enctype="multipart/form-data">
    <div class="card">

        <div class="card-header">
            <h5>Inserat bearbeiten</h5>
        </div>

        <div class="card-body">

            <input hidden asp-for="Id" />

            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="JobTitle" type="text" placeholder="Bitte trage eine Jobbeschreibung ein" />
                </div>

                <div class="col">
                    <input class="form-control" asp-for="JobLocation" type="text" placeholder="Bitte trage einen Ort ein" />
                </div>
            </div>
        </div>

        <div class="row form-group">
            <div class="col">
                <textarea rows="6" class="form-control" asp-for="Description" placeholder="Bitte trage eine Beschreibung ein"></textarea>
            </div>
        </div>

        <div class="card-body form-group">

            <div class="row">
                <div class="col-6">
                    <input class="form-control" asp-for="Salary" type="number" placeholder="Bitte gebe Gehalt" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col-6">
                    <div class="col-form-label">
                        Wann startet der Job?
                    </div>
                    <input class="form-control" asp-for="StartDate" type="date" />
                </div>
            </div>

            <hr />
            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="CompanyName" type="text" placeholder="Firmenname" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactWebsite" type="url" placeholder="Website (URL)" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="ContactPhone" type="tel" placeholder="Telefonnummer" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactMail" type="email" placeholder="Email-Adresse" />
                </div>
            </div>

            <div class="col">
                <input class="form-control" asp-for="JobLocation" type="text" placeholder="Bitte trage einen Ort ein" />
            </div>

            <div class="row form-group">
                <div class="col">
                    <label> Bild</label>
                    <input class="form-control-file" name="file" type="file" />
                </div>
            </div>

            <div class="card-footer">
                <button class="btn btn-primary" type="submit">Speichern</button>
            </div>
        </div>
    </div>
</form>

Worktastic/Views/JobPosting/Index.cshtml
@model List<JobPosting>

@{
    ViewData["Title"] = "Deine Inserate";
}

<a class="btn btn-primary" asp-controller="JobPosting" asp-action="CreateEditJobPosting"> Neues Inserat anlegen</a>

<hr />
<table id="jobPostingTable" class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>
                Job Titel
            </th>
            <th>
                Ort
            </th>
            <th>
                Firmenname
            </th>
            <th>
                Aktionen
            </th>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (JobPosting jobPosting in Model)
            {
                <tr>
                    <td>
                        @jobPosting.JobTitle
                    </td>
                    <td>
                        @jobPosting.JobLocation
                    </td>
                    <td>
                        @jobPosting.CompanyName
                    </td>
                    <td>
                        <a asp-route-id="@jobPosting.Id" asp-controller="JobPosting" asp-action="CreateEditJobPosting" class="btn btn-warning">Edit</a>
                        <button onclick="onClickedDeleteButton(@jobPosting.Id)" class="btn btn-danger">Löschen</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

@section Scripts {
    <script>
        debugger;
        $(document).ready(function () {
            $('#jobPostingTable').DataTable();
        });

        function onClickedDeleteButton(id) {
            debugger;
            Swal.fire({
                title: 'Möchtest du das Inserat wirklich löschen?',
                icon: 'error',
                showCloseButton: true,
                focusConfirm: false,
                confirmButtonText:
                    'Ja, löschen'
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) 
                {

                    //Backend call to delete job posting by Id
                    // Ajax: Asynchronous javascript calls is the best option
                    $.ajax
                        ({
                            // Method vom Type POST:
                            type: "POST",
                            url: "@Url.Action("DeleteJobPostingById")",
                            data: { id: id }, // der erste id ist der frei wählbare Name, der zweite id ist der Parameter
                            success: function (msg) {
                                Swal.fire('Wurde gelöscht', '', 'success').then((result) => {
                                    location.reload();
                                })
                            },
                            error: function (msg) {
                                Swal.fire('Ups, etwas ist schiefgelaufen', '', 'error')
                            }
                        });
                }
            })
        }
    </script>
}